location ~ ^/(admin-old|\.env|phpmyadmin|wp-login\.php|backup\.zip|debug|console-login)$ {
    proxy_pass http://secpilot-api:8000/api/v1/honeypot/events;
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header User-Agent $http_user_agent;
}
